### ISSUE TITLE
x64dbg process list NtQuerySystemInformationEx returns ACCESS_VIOLATION

### ISSUE THREAD

**Issue by DebugView12** [btbd/access#8] opened 2020-08-13 23:25 UTC
Hi thanks for your other fix it works with process hacker now but I have found another problem where opening up the process list in x64dbg is empty because NtQuerySystemInformationEx returns status_access_violation.

**Comment by btbd** [comment] 2020-08-14 01:52
@DebugView12 I can't appear to reproduce this, but you could try changing [this line](https://github.com/btbd/access/blob/noseh/Driver/core.c#L91) to
```
(args->SystemInformation && !ProbeUserAddress(args->SystemInformation, args->SystemInformationLength, sizeof(LONG))) ||
```
However, for x64dbg I will note that nothing related to debugging is implemented as that is not the purpose of this project.

**Comment by DebugView12** [comment] 2020-08-16 05:28
Hi sorry for the late reply, I understand it's nothing to do with the project I'm sorry about that. I have another issue I don't think it's the appropriate place to discuss this but I have no other way contacting you, I'm trying to replace MmCopyVirtualMemory with memcpy (I am not manual mapping so I have SEH) but it doesn't seem to work anymore I don't see the issue in the code I replaced it with https://image.prntscr.com/image/GLmTQ3JyTkypvqIfh7SM1A.png

**Comment by btbd** [comment] 2020-08-16 05:41
@DebugView12 No worries. With regards to the code in the screenshot, `args->Buffer` is a user buffer in the context of the calling process. By doing `KeAttachProcess` to a different process that user buffer is no longer valid. You need to create an intermediate buffer in the system address space that is the destination of the `memcpy`. Also `SYSTEM_SERVICE_EXCEPTION` is a bugcheck code, your exception handler be `EXCEPTION_EXECUTE_HANDLER`.

**Comment by DebugView12** [comment] 2020-08-16 06:11
Thank you for your quick answer btbd, I attempted what you said but I am still having troubles can't figure it out. I'm trying my best to not lazily rely on you https://prnt.sc/u0ch7h

**Comment by btbd** [comment] 2020-08-16 06:26
@DebugView12 You should learn to use a debugger or at least print out errors. `PsLookupProcessById` accepts a process ID not a process handle (especially not `NtCurrentProcess` which returns `-1` to represent the current process), so this already fails. Once you detach from the target process, you don't need to reattach back to the source process since the detach already put you back in the source process' address space. You can look at some other syscall implementations in the project if you need an example. However, I'm not quite sure why you need to do any of this -- `MmCopyVirtualMemory` already does all of this for you. Anyways, I'm going to close this issue as I'm not here to be a beginners programming helpline and it's clear you need to do more learning on your own.

**Closed by btbd** 2020-08-16 06:26 UTC

**Comment by DebugView12** [comment] 2020-08-16 06:30
I understand that MmCopyVirtualMemory does all that but there is a reason why I need to use memcpy. An irrelevant reason.
